# SOURCE: PotsdamIRRG
# TARGET: Vaihingen
#---REVERSE---
SOURCE: Paris
TARGET: Chicago

NUM_WORKERS: 8
GPU_ID: 0
EXP_NAME: 'reproduce_Paris_Chi'

TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv3
  #--REVERSE--
  #/root/code/CCA-LGFA/on_vaih_model_13000.pth
  BATCH_SIZE_TARGET: 1
  BATCH_SIZE_SOURCE: 1
  MULTI_LEVEL: False
  LAMBDA_SEG_MAIN: 1.0
  LAMBDA_SEG_AUX: 0.1
  LAMBDA_SEG_LOW: 0.1
  LAMBDA_ADV_MAIN: 0.1
  LAMBDA_ADV_AUX: 0.1
  LAMBDA_ADV_LOW: 0.1
TEST:
  MODE: best