SOURCE: Paris
TARGET: Chicago
#---REVERSE---
#SOURCE: Vaihingen
#TARGET: PotsdamIRRG

DATA_LIST_TARGET: ../CCDA/easy_split.txt
NUM_WORKERS: 8
GPU_ID: 2
EXP_NAME: 'reproduce_Paris_Chi_FL' #FL represents the Feature-Level Adaptation
                                        #EL represents the Entropy-Level Adaptation
GPU_PARALLEL: 0 #  1:for gpu parallel 0:not
TRAIN:
  DA_METHOD: AdvEnt
  MODEL: DeepLabv3
  #GANLOSS: BCE
  RESTORE_FROM: ../../pretrained_models/Paris_source_model.pth
  # ../../experiments/snapshots/reproduce_PotsIRRG_Vaih_FL/model_900.pth
  # ../../pretrained_models/PotsIRRG_source_model.pth
  # Models in different stages:
  # /root/code/CCDA_LGFA/ADVENT/pretrained_models/PotsIRRG_source_model.pth
  # /root/code/CCDA_LGFA/ADVENT/experiments/snapshots/reproduce_PotsIRRG_Vaih_FL/model_1800.pth
  # /root/code/CCDA_LGFA/ADVENT/experiments/snapshots/reproduce_PotsIRRG_Vaih_EL/model_2700.pth

  #--REVERSE--
  # Models in different stages:
  #/root/code/CCDA_LGFA/ADVENT/on_vaih_model_13000.pth

  MULTI_LEVEL: False
  LAMBDA_SEG_MAIN: 1.0
  LAMBDA_SEG_AUX: 0.1
  LAMBDA_SEG_LOW: 0.1
  LAMBDA_ADV_MAIN: 0.1
  LAMBDA_ADV_AUX: 0.1
  LAMBDA_ADV_LOW: 0.1
TEST:
  MODE: best